Add back serialization of json in row_to_singer_message() to try and fix serialization error
In _format_message() at `orjson.dumps(message.asdict(), default=_orjson_default).decode()`
causing

> TypeError: Type is not JSON serializable